version: '3'
services:
  application:
    container_name: my_app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
